# Generated by Django 5.1.5 on 2025-02-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_employee_address_alter_employee_employeeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
