# Generated by Django 5.1.5 on 2025-02-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_employee_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='add',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeid',
            new_name='emp',
        ),
    ]
