# Generated by Django 5.1.5 on 2025-02-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_rename_address_employee_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='add',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
